"""services

Revision ID: 503c9e1681d4
Revises: 07ec968bb701
Create Date: 2026-08-02 21:49:53.311382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503c9e1681d4'
down_revision = '07ec968bb701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=600), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('link_url', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index('ix_services_order', ['is_published', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_slug'), ['slug'], unique=True)

    op.create_table('service_images',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_images_service_id'), ['service_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_images_service_id'))

    op.drop_table('service_images')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_slug'))
        batch_op.drop_index('ix_services_order')

    op.drop_table('services')
    # ### end Alembic commands ###
