"""staff members

Revision ID: 74feb9ce3cb5
Revises: 124b9d4f06bb
Create Date: 2026-08-02 06:09:46.580399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74feb9ce3cb5'
down_revision = '124b9d4f06bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram', sa.String(length=255), nullable=True),
    sa.Column('vk', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.create_index('ix_staff_order', ['is_published', 'sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_order')

    op.drop_table('staff_members')
    # ### end Alembic commands ###
